### PR TITLE
triple quotes memory leak -> fix

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by srghma** [comment]
@kayhide maybe You know why this error happens? :pray: 

https://github.com/neovim/neovim/issues/30913

**Comment by srghma** [comment]
Now I have an error on https://github.com/kayhide/tree-sitter-idris/pull/3/commits/76d75b25ca72432064a7dc55e4f42c290e637daf

```
 ~/projects/tree-sitter-idris   main  npm run test

> tree-sitter-idris@0.0.1 test
> node --test bindings/node/*_test.cjs

✖ can load grammar (4.30676ms)
  AssertionError [ERR_ASSERTION]: Got unwanted exception.
  Actual message: "/home/srghma/projects/tree-sitter-idris/build/Release/tree_sitter_idris_binding.node: undefined symbol: tree_sitter_idris_external_scanner_create"
      at TestContext.<anonymous> (/home/srghma/projects/tree-sitter-idris/bindings/node/binding_test.cjs:8:10)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:930:25)
      at Test.start (node:internal/test_runner/test:829:17)
      at startSubtestAfterBootstrap (node:internal/test_runner/harness:289:17) {
    generatedMessage: false,
    code: 'ERR_ASSERTION',
    actual: Error: /home/srghma/projects/tree-sitter-idris/build/Release/tree_sitter_idris_binding.node: undefined symbol: tree_sitter_idris_external_scanner_create
        at Module._extensions..node (node:internal/modules/cjs/loader:1717:18)
        at Module.load (node:internal/modules/cjs/loader:1317:32)
        at Module._load (node:internal/modules/cjs/loader:1127:12)
        at TracingChannel.traceSync (node:diagnostics_channel:315:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
        at Module.require (node:internal/modules/cjs/loader:1339:12)
        at require (node:internal/modules/helpers:135:16)
        at load (/home/srghma/projects/tree-sitter-idris/node_modules/node-gyp-build/node-gyp-build.js:22:10)
        at Object.<anonymous> (/home/srghma/projects/tree-sitter-idris/bindings/node/index.cjs:3:43)
        at Module._compile (node:internal/modules/cjs/loader:1546:14),
    expected: undefined,
    operator: 'doesNotThrow'
  }

ℹ tests 1
ℹ suites 0
ℹ pass 0
ℹ fail 1
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 40.507796

✖ failing tests:

test at bindings/node/binding_test.cjs:6:1
✖ can load grammar (4.30676ms)
  AssertionError [ERR_ASSERTION]: Got unwanted exception.
  Actual message: "/home/srghma/projects/tree-sitter-idris/build/Release/tree_sitter_idris_binding.node: undefined symbol: tree_sitter_idris_external_scanner_create"
      at TestContext.<anonymous> (/home/srghma/projects/tree-sitter-idris/bindings/node/binding_test.cjs:8:10)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:930:25)
      at Test.start (node:internal/test_runner/test:829:17)
      at startSubtestAfterBootstrap (node:internal/test_runner/harness:289:17) {
    generatedMessage: false,
    code: 'ERR_ASSERTION',
    actual: Error: /home/srghma/projects/tree-sitter-idris/build/Release/tree_sitter_idris_binding.node: undefined symbol: tree_sitter_idris_external_scanner_create
        at Module._extensions..node (node:internal/modules/cjs/loader:1717:18)
        at Module.load (node:internal/modules/cjs/loader:1317:32)
        at Module._load (node:internal/modules/cjs/loader:1127:12)
        at TracingChannel.traceSync (node:diagnostics_channel:315:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
        at Module.require (node:internal/modules/cjs/loader:1339:12)
        at require (node:internal/modules/helpers:135:16)
        at load (/home/srghma/projects/tree-sitter-idris/node_modules/node-gyp-build/node-gyp-build.js:22:10)
        at Object.<anonymous> (/home/srghma/projects/tree-sitter-idris/bindings/node/index.cjs:3:43)
        at Module._compile (node:internal/modules/cjs/loader:1546:14),
    expected: undefined,
    operator: 'doesNotThrow'
  }
```

**Comment by srghma** [comment]
@kayhide could You add me as maintainer?

**Comment by kayhide** [comment]
@srghma Hi, thank you for your PR. It looks good.

**Comment by kayhide** [comment]
> @kayhide could You add me as maintainer?

Okay, I will add you as a maintainer.

**Comment by srghma** [comment]
AWE-SOME!!!!))))

**Pull request merged**
